### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dinever** [dinever/dingo#7]
Post:

- [ ] Post category #3 
- [ ] Post cover image #2 
- [ ] Post sharing link

Others:

- [ ] Messages
- [ ] Search

Dashboard:

- [ ] Page view
- [ ] Top pages

Front-end:

- [ ] Tidy SCSS files #4
- [ ] Rewrite admin dashboard using AJAX #5 

Model/Database:

- [ ] Tidy `sql_stmt.go`
- [ ] Migration from Ghost

API:

- [ ] Restful API support

**Comment by samdfonseca** [comment]
@dinever I've got some free time over the next few days to work on #6 here, and it'd be great to get a few more details on what you're looking for.

**Comment by dinever** [comment]
@samdfonseca Let's try to implement `/api/posts` first. We can have several parameters to filter the result. For example:

`/api/posts?page=1&limit=5&order=published_at` should return the first 5 posts order by the field `published_at`

**Comment by bentranter** [comment]
@samdfonseca wanna work together, or split the work up on the API? I was going to work on it for awhile tonight, I'm on the Gophers Slack if you want to communicate there

**Comment by samdfonseca** [comment]
@bentranter yea that sounds great. i went ahead and make a dingo gitter room (https://gitter.im/dingoblog) but if slack works better for you im down to use that

**Comment by TimothyYe** [comment]
Do we have a plan to manage all the vendor packages? 
There are some Go package management tools to choose:

Godep
Govendor
godm
vexp
gv
gvt - Recursively retrieve and vendor packages.
govend
Glide

**Comment by bentranter** [comment]
I happened to see on my GitHub feed that @samdfonseca created a vendor branch the other day with Godep (creepy I know, haha). I think I've tried every vendoring tool so far and don't really have a preference, but Godep is a good one. Makes it really easy to update vendored packages too which is nice.

**Comment by TimothyYe** [comment]
Yep, I tried both Godep & [Glide](https://github.com/Masterminds/glide) they are both good options.

**Comment by samdfonseca** [comment]
haha i thought i snuck that in @bentranter. yea that was made out of frustration ive been having dealing with different versions of dependencies. let me know if i should pr it and ill sort out any conflicts if there are any.

**Comment by bentranter** [comment]
@samdfonseca I think you should PR it, I'm cool with using Godep
